[workspace]
members = [
  "libs/bsp",
  "libs/cpio",
  "libs/cpu",
  "libs/device",
  "libs/devicetree",
  "libs/library",
  "libs/vfs",
  "bins/bootloader",
  "bins/kernel-transfer",
  "bins/ppos",
  "bins/system-call-test-program",
  "bins/user-space-test-program",
]
resolver = "2"
